trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - .editorconfig
    - .gitignore

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - .editorconfig
    - .gitignore

name: 8.1.$(Build.BuildId)

variables:
- name: VMImage
  value: 'windows-latest'
- name: BuildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: Release
- group: 'Code Signing'
- group: 'GitHub Release'


stages:
- stage: build
  displayName: Build NuGet Packages
  jobs:
  - job: buildJob
    displayName: Build Prism.Plugin.Popups
    pool:
      vmImage: $(VMImage)
      demands:
      - MSBuild
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: NuGetToolInstaller@1
      displayName: Use Latest NuGet
      inputs:
        checkLatest: true

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        feedsToUse: config
        nugetConfigPath: NuGet.config

    - task: MSBuild@1
      displayName: Build Prism.Plugin.Popups
      inputs:
        solution: Prism.Plugin.Popups.sln
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/p:DebugType=portable /p:JavaSdkDirectory="$(JAVA_HOME)"'

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: |
         **\*.Tests.csproj
        arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings /p:DebugType=portable --no-build
      displayName: Run Tests

    - powershell: ./Sign-Packages.ps1
      workingDirectory: build
      displayName: Authenticode Sign Artifacts
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        SignClientClientId: $(SignClientClientId)
        SignClientTenantId: $(SignClientTenantId)
        SignServiceResourceId: $(SignServiceResourceId)
      condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

    - task: PublishPipelineArtifact@1
      displayName: Publish Package Artifacts
      inputs:
        artifactName: NuGet
        targetPath: '$(Build.ArtifactStagingDirectory)'
      condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
- stage: deploy
  displayName: Deploy CI Feed
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: SponsorConnect
    displayName: SponsorConnect.dev
    environment: SponsorConnect
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            displayName: NuGet Push
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.snupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'SponsorConnect'

- stage: deployNuGetOrg
  displayName: 'Deploy to NuGet.org'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['IS_RELEASE'], 'true'))
  jobs:
  - deployment: NuGet
    displayName: NuGet.org
    environment: NuGet
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: Get Build Resources

          - powershell: build/Process-Release.ps1
            displayName: Process Artifacts for Release
          - powershell: |

            displayName: Process Artifacts for Deployment
          - task: GitHubRelease@1
            displayName: 'Create GitHub Release'
            inputs:
              gitHubConnection: GitHub
              title: '$(ReleaseDisplayName)'
              tag: 'v$(VersionName)'
              isPreRelease: $(IS_PREVIEW)
              assets: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.snupkg'
              addChangeLog: true
              isDraft: true
          - task: NuGetCommand@2
            displayName: NuGet Push
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.snupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'NuGet'
